// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAwO581D5NjNfJI0yMThS8yquZwW2GGUM',
    appId: '1:677359964042:web:ec7b877ebf2e0065b84273',
    messagingSenderId: '677359964042',
    projectId: 'finance-ad14e',
    authDomain: 'finance-ad14e.firebaseapp.com',
    storageBucket: 'finance-ad14e.appspot.com',
    measurementId: 'G-W0XNWY6L96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Ld_Dks7_DHWFStb0Y_wBL6dt6SSBqjk',
    appId: '1:677359964042:android:5635c3b1e015d869b84273',
    messagingSenderId: '677359964042',
    projectId: 'finance-ad14e',
    storageBucket: 'finance-ad14e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfqde2P-6CkgCukG9CJV5HGPlNOUevvy0',
    appId: '1:677359964042:ios:72edb64cf60747ccb84273',
    messagingSenderId: '677359964042',
    projectId: 'finance-ad14e',
    storageBucket: 'finance-ad14e.appspot.com',
    iosClientId: '677359964042-ge5gvov63j9icmd3lgqgbs6p19rtkdug.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinanceGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfqde2P-6CkgCukG9CJV5HGPlNOUevvy0',
    appId: '1:677359964042:ios:72edb64cf60747ccb84273',
    messagingSenderId: '677359964042',
    projectId: 'finance-ad14e',
    storageBucket: 'finance-ad14e.appspot.com',
    iosClientId: '677359964042-ge5gvov63j9icmd3lgqgbs6p19rtkdug.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinanceGetx',
  );
}
